<?php
/**
 *
 * @ IonCube v8.3 Loader By DoraemonPT
 * @ PHP 5.3
 * @ Decoder version : 1.0.0.7
 * @ Author     : DoraemonPT
 * @ Release on : 09.05.2014
 * @ Website    : http://EasyToYou.eu
 *
 **/

echo '		<!-- <script type="text/javascript" src="';
echo '"></script>-->
		<!--<script type="text/javascript" src="';
echo '"></script>-->

		<!--<script type="text/javascript" src="';
echo '"></script>-->

		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/jquery-ui.js' );
echo '"></script>

		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/dol_popup_js.js' );
echo '"></script>
		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/jquery-ui-1.9.2.custom.min.js' );
echo '"></script>
		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/selectbox/js/jquery.selectbox-0.2.js' );
echo '"></script>
		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/jquery.mCustomScrollbar.concat.min.js' );
echo '"></script>

		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/upload/js/vendor/jquery.ui.widget.js' );
echo '"></script>
		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/upload/js/tmpl.min.js' );
echo '"></script>
		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/upload/js/load-image.all.min.js' );
echo '"></script>
		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/upload/js/canvas-to-blob.min.js' );
echo '"></script>
		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/upload/bootstrap-3.2.0/js/bootstrap.min.js' );
echo '"></script>
		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/upload/js/jquery.blueimp-gallery.min.js' );
echo '"></script>
		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/upload/js/jquery.iframe-transport.js' );
echo '"></script>
		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/upload/js/jquery.fileupload.js' );
echo '"></script>
		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/upload/js/jquery.fileupload-process.js' );
echo '"></script>
		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/upload/js/jquery.fileupload-validate.js' );
echo '"></script>

		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/upload/js/jquery.fileupload-ui.js' );
echo '"></script>
		<script type="text/javascript" src="';
echo $this->getJSUrl( 'all/standalone/upload/js/main.js' );
echo '"></script>

';

$params = $this->getRequest(  )->getParams(  );

$id = $params['id'];

if (array_key_exists( 'productIds', $params )) {

	$product_ids = $params['productIds'];

	if ($product_ids) {

		$product_ids = explode( '|', $product_ids );
	}
}
else {
	$product_ids = array(  );
}


$is_last_level = $this->getData( 'is_last_level' );

if (!$is_last_level) {
	$is_last_level = false;
}


$hide_add_to_cart =$this->getData('hide_add_to_cart');

if (!$hide_add_to_cart) {
	$hide_add_to_cart = 'false';
}


$hide_design_your_own = $this->getData( 'hide_design_your_own' );

if (!$hide_design_your_own) {
	$hide_design_your_own = 'false';
}


$configurable_list = Mage::helper('template')->getAllConfigurableProducts();
echo '
<script type="text/javascript" src="/js/all/common/product.js"></script>
';

$is_scp_enabled = Mage::getStoreConfig( 'dol/catalog_setting/scp_enabled' );

if ($is_scp_enabled) {
	echo '<script type="text/javascript" src="';
	echo $this->getSkinUrl( 'js/scp_product_extension.js' );
	echo '"></script>
';
}

echo '<script type="text/javascript">
//<![CDATA[

var optionsPrice;

jQuery.cachedScript = function(url, options) {
	// allow user to set any option except for dataType, cache, and url
	options = $j.extend(options || {}, {
	dataType: "script",
	cache: true,
	url: url
	});
	// Use $.ajax() since it is more flexible than $.getScript
	// Return the jqXHR object so we can chain callbacks
	return jQuery.ajax(options);
};

function getProductPricing(product_id){
	if(product_id!=undefined){
		url = \'/catalog/product/ajaxsingle\';
		document.getElementById(\'pricing\').innerHTML = \'<div align="center"><img src="';
echo $this->getSkinUrl( 'images/opc-ajax-loader.gif' );
echo '"/><br /><br /></div>\';

		$j.ajax({
			url: url,
			data: {\'id\':product_id, \'hide_add_to_cart\':';
echo $hide_add_to_cart;
echo ',\'hide_design_your_own\':';
echo $hide_design_your_own;
echo '},
			dataType: \'text\',
			success: function(data) {
				$j.cachedScript("/catalog/product/js/id/"+product_id)
					.done(function(script, textStatus) {
						productAddToCartForm = new VarienForm(\'product_addtocart_form\');
						productAddToCartForm.submit = function(button, url) {
				            if (this.validator.validate()) {
				                var form = this.form;
				                var oldUrl = form.action;

				                document.getElementById(\'price_box_data\').value = $$(\'div.price-box\')[0].innerHTML;

				                if (url) {
				                   form.action = url;
				                }
				                var e = null;
				                try {
				                    this.form.submit();
				                } catch (e) {
				                }
				                this.form.action = oldUrl;
				                if (e) {
				                    throw e;
				                }

				                if (button && button != \'undefined\') {
				                    button.disabled = true;
				                }
				            }
				        }.bind(productAddToCartForm);

				        ';

$is_scp_enabled = Mage::getStoreConfig( 'dol/catalog_setting/scp_enabled' );

if ($is_scp_enabled) {
	echo '						$(\'product_addtocart_form\').getElements().each(function(el) {
					        if(el.type == \'select-one\') {
					            if(el.options && (el.options.length > 1)) {
					                el.options[0].selected = true;
					                spConfig.reloadOptionLabels(el);
					            }
					        }
					    });
					    ';
}

echo '
					    if(spConfig.settings[0]!=undefined && spConfig.settings[0].length>1){
							for(var i=0; i<10; i++){
								if(spConfig.settings[i]!=undefined){
									if(spConfig.settings[i].length>1){
										spConfig.settings[i].selectedIndex = 1;
										spConfig.configureElement(spConfig.settings[i]);
									}else{
										break;
									}
								}else{
									break;
								}
							}
					    }
				})
				data = data.replace(/[*]/g,"");
				data = data.replace("Required Fields","");
				data = data.replace("Availability: In stock.","");
				data = data.replace("availability","availability hide");
				data = data.replace("product-options","product-options no-margin-top");
				data = data.replace("class=\"label\" id=\"configurable-price-from", "class=\"label hide\" id=\"configurable-price-from");
				data = data.replace(/(\r\n|\n|\r)/gm,"");
				data = data.replace("p>            <div class=\"price-box\">","p> <div class=\"price-box hide\">");
				data = data.replace("regular-price","regular-price hide");
				data = data.replace("</div>        <label id=\"ajax_qty\"","<label id=\"ajax_qty\"");
				data = data.replace("</div>                <label id=\"ajax_qty\"","<label id=\"ajax_qty\"");
				data = data.replace("</div>                <label style=\"margin-left:50px;\" for=\"qty\" id=\"ajax_qty\"","<label style=\"margin-left:50px;\" for=\"qty\" id=\"ajax_qty\"");
				data = data.replace("</div>                <label for=\"qty\" style=\"margin-left:50px;\" id=\"ajax_qty\"","<label for=\"qty\" style=\"margin-left:50px;\" id=\"ajax_qty\"");

				data = data.replace("<div class=\"add-to-cart\">","</div><div class=\"add-to-cart\">");

				document.getElementById(\'pricing\').innerHTML = data;
				decorateGeneric($$(\'#product-options-wrapper dl\'), [\'last\']);


				jQuery("#cart_add").click(function(){
					cart_qty=parseInt(jQuery("#qty").val());
					jQuery("#qty").val(cart_qty+1);
					return false;
				});
					jQuery("#cart_remove").click(function(){
						cart_qty=parseInt(jQuery("#qty").val());
						if (cart_qty>0)
						jQuery("#qty").val(cart_qty-1);
						return false;
				});


			}
		});
	}
}

function removeRequiredClass(ab){
	$j("#plain_product").val(0);
	$j("input[type=\'file\'].product-custom-option").removeClass(\'required-entry\');
	$j("input[type=\'file\'].product-custom-option").first().removeClass(\'required-entry\');
	$j("#advice-required-entry-options_1_file").addClass(\'validation-advice hide\');

	productAddToCartForm.submit(ab);
}
function addRequiredClass(){
	$j("#plain_product").val(1);
	$j("#advice-required-entry-options_1_file").removeClass(\'validation-advice hide\');
	$j("#advice-required-entry-options_1_file").addClass(\'validation-advice\');
	$j("input[type=\'file\'].product-custom-option").first().addClass(\'required-entry\');
}

function started(){

	$j("#alone").addClass("frame_wrapper");
	$j(".step1").hide();
	$j(".step2").show();


	$j("#choose_dyo").hide();
	$j("#new_design_own").show();
	$j("#choose_upload").hide();
	$j("#new_upload_own").show();


	productId = $j("#configurable_product_id").val();

	browse = document.getElementById("demo-frame").src;
    $j.ajax({
      type: \'GET\',
      url: browse,
      data:{\'pid\':productId},
      complete: function(data){
	 	 var result = $j(data.responseText).find(\'.category-products\').html();
     	 if(result == null){
     			$j(".choose_content_1").addClass(\'design\');
				$j(".choose_content_3").addClass(\'upload\');
	     		$j(".choose_content_1, .choose_content_2").css({"width":"478px"});
	     		$j(".choose_content_3").css({"margin-left":"50px"});
	     		//$j("#choose_upload").css({"margin-left":"130px"});
				$j(\'.choose_content_2\').hide();
     		}else{
     			$j(".choose_content_1").removeClass(\'design\');
				$j(".choose_content_3").removeClass(\'upload\');
     			$j(\'.choose_content_2\').show();
     			$j(".choose_content_1, .choose_content_2, .choose_content_3").css({"width":"318px"});
	     		$j(".choose_content_3").css({"margin-left":"0px"});
     		}

     	$j(".category-image #configurable_product_id").addClass("sp_selector");
     	var design_browse_upload = \'What would you like to do for your \' + $j(".category-image #configurable_product_id").val(this).text() + \' ? \';
		$j(".ui-dialog-titlebar .ui-dialog-title").text(design_browse_upload);

		var design_pricing = \'Finalize Options for your \' + $j(".sp_selector").val(this).text();
		$j("#choose_dyo").click(function(){
			$j(".ui-dialog-titlebar .ui-dialog-title").text(design_pricing);
			$j(".ui-dialog-titlebar .ui-dialog-title").append("<a id=\'change_product\'>[Change Product]</a>");
		});

		var browse_templates = \'Browse Designs of \' + $j(".sp_selector").val(this).text();
			$j("#choose_browse").click(function(){
				$j(".ui-dialog-titlebar .ui-dialog-title").text(browse_templates);
				$j(".ui-dialog-titlebar .ui-dialog-title").append("<a id=\'change_product\'>[Change Product]</a>");
			});

		var upload_pricing = \'Finalize Options for your \' + $j(".sp_selector").val(this).text();
		$j("#choose_upload").click(function(){
			$j(".ui-dialog-titlebar .ui-dialog-title").text(upload_pricing);
			$j(".ui-dialog-titlebar .ui-dialog-title").append("<a id=\'change_product\'>[Change Product]</a>");
		});


		$j("#browse_prevframe").click(function(){
			var browse_prevframe = \'What would you like to do for your \' + $j(".sp_selector").val(this).text() + \' ? \';
			$j(".ui-dialog-titlebar .ui-dialog-title").text(browse_prevframe);
			$j(".ui-dialog-titlebar .ui-dialog-title").append("<a id=\'change_product\'>[Change Product]</a>");
		});


		$j("#upload_own").click(function(){
			var upload_files = \'Upload Files for your \' + $j(".sp_selector").val(this).text();
			$j(".ui-dialog-titlebar .ui-dialog-title").text(upload_files);
			$j(".ui-dialog-titlebar .ui-dialog-title").append("<a id=\'change_product\'>[Change Product]</a>");
		});

		$j("#upload_prevframe").click(function(){
			var upload_pricing = \'Finalize Options for your \' + $j(".sp_selector").val(this).text();
			$j(".ui-dialog-titlebar .ui-dialog-title").text(upload_pricing);
			$j(".ui-dialog-titlebar .ui-dialog-title").append("<a id=\'change_product\'>[Change Product]</a>");
		});

		$j("#design_upload_prevframe").click(function(){
			var design_browse_upload = \'What would you like to do for your \' + $j(".sp_selector").val(this).text() + \' ? \';
			$j(".ui-dialog-titlebar .ui-dialog-title").text(design_browse_upload);
			$j(".ui-dialog-titlebar .ui-dialog-title").append("<a id=\'change_product\'>[Change Product]</a>");
		});


		/*Change Product Link*/
		$j(".ui-dialog-titlebar .ui-dialog-title").append("<a id=\'change_product\'>[Change Product]</a>");
		$j("#change_product").click(function(){
			$j("#choose_content").hide();
			$j(".step3").hide();
			$j(\'option:selected\', this).removeAttr(\'selected\');
			$j(".sp_selector").removeClass("sp_selector");
			$j("#change_product").hide();
			$j("#nextframe_choose").hide();
			$j(".ui-dialog-titlebar .ui-dialog-title").text("Lets get started...");
			$j(".select_product .sbHolder .sbSelector").text("Choose one product...");
			$j(".select_content_1 h2").slideDown("slow");
			$j(".select_product").slideDown("slow");
			$j(".select_content_1").css({"border-bottom":"none"});
			$j(".instant_pricing_container").hide();
		});

      }
    });



	$j("#alone").dialog({
		autoOpen: true,
		modal: true,
		width: 960,
		height: 600,
		dialogClass:\'fixedpos\',
		zIndex:\'10000\',
		resizable:\'false\',
		show:\'slide\',
		draggable: true,
		closeOnEscape: false,
		//close: function(ev, ui) {parent.window.location.reload();}
	});

}
//]]>
</script>

	<div class="sidebar-box">
		<select id="configurable_product_id" name="configurable_product_id" onchange="getProductPricing(this.value);" class="sidebar-inner-select" style="background-color:#fff;display:none;">
			';
foreach ($configurable_list as $product) {


	if (( ( !$is_last_level || !$product_ids ) || ( $is_last_level && in_array( $product->getId(  ), $product_ids ) ) )) {
		echo '			<option value="';
		echo $product->getId(  );
		echo '" >';
		echo Mage::helper( 'catalog' )->__( $product->getName(  ) );
		echo '</option>
			';
		continue;
	}
}

echo '		</select>
		<div id="pricing"></div>
	</div>

<script type="text/javascript">
<!--
	getProductPricing($j("#configurable_product_id").first().val());
//-->
</script>
<script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm(\'product_addtocart_form\');

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods[\'required-entry\'];
                delete Validation.methods[\'validate-one-required\'];
                delete Validation.methods[\'validate-one-required-by-name\'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    document.getElementById(\'price_box_data\').value = $$(\'div.price-box\')[0].innerHTML;
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
</script>

<div id="alone" title="';
echo Mage::helper( 'cms' )->__( 'Lets get started...' );
echo '">
';

$alone = $this->getLayout()->createBlock('core/template')->setTemplate('web4pro/pixopa/standalone_category.phtml');
//->setTemplate('pixopa/dol/standalone/standalone_category.phtml');
echo $alone->toHtml(  );
echo '
</div>


';
?>
