
<script type="text/javascript">
$jf = jQuery.noConflict();
	$jf(function(){
		
		var gallery = $jf('#images');
		gallery.exposure({controlsTarget : '#controls',
			controls : { prevNext : true, pageNumbers : true, firstLast : false },
			visiblePages : 2,
			//autostartSlideshow:true,	
			
			slideshowControlsTarget : '#slideshow',
			onThumb : function(thumb) {
				
				var li = thumb.parents('li');				
				var fadeTo = li.hasClass($jf.exposure.activeThumbClass) ? 1 : 0.3;
				
				thumb.css({display : 'none', opacity : fadeTo}).stop().fadeIn(200);
				
				thumb.hover(function() { 
					thumb.fadeTo('fast',1); 
				}, function() { 
					li.not('.' + $jf.exposure.activeThumbClass).children('img').fadeTo('fast', 0.3); 
				});
			},
			onImage : function(image, imageData, thumb) {
				// Fade out the previous image.
				image.siblings('.' + $jf.exposure.lastImageClass).stop().fadeOut(500, function() {
					$jf(this).remove();
				});
				
				// Fade in the current image.
				image.hide().stop().fadeIn(1000);

				// Fade in selected thumbnail (and fade out others).
				if (gallery.showThumbs && thumb && thumb.length) {
					thumb.parents('li').siblings().children('img.' + $jf.exposure.selectedImageClass).stop().fadeTo(200, 0.3, function() { $jf(this).removeClass($jf.exposure.selectedImageClass); });			
					thumb.fadeTo('fast', 1).addClass($jf.exposure.selectedImageClass);
				}
			},
			onPageChanged : function() {
				// Fade in thumbnails on current page.
				gallery.find('li.' + $jf.exposure.currentThumbClass).hide().stop().fadeIn('fast');
			}
			   
		});
		
				   
	});
</script>
<?php if($this->getConfig('enabled')){ ?>	  <!-- start enable -->
	<?php $cur_store = Mage::app()->getStore()->getId() ?>
<div id="main" class="container relative">
    
    <div id="exposure"></div>
    <div class="panel">
        <ul id="images">            
				<?php
                // Get data banner
                $slide = $this->getDataBanner7();
                $path = Mage::getBaseUrl('media');					
                $qty_Item = $this->getConfig('qty_item');
                ?>
                <?php
                $i = 1;
                foreach($slide as $s)
                {
                if($i <= $qty_Item) {
                //Get images slide show
                $st1 = $s['image'];
									$thumb = $s['thumbnailimage'];
									
									$p1 = strpos($st1,'banner7');
									$thumb1 = strpos($thumb,'banner7');
									
									$st2 = substr($st1,$p1+7);
									$thumb2 = substr($thumb,$thumb1+7);
									
									$p2 = strpos($st2,'"');
									$thimage2 = strpos($thumb2,'"');
									
									$imag = substr($st2,0,$p2);
									$thumb_imag = substr($thumb2,0,$thimage2);
                ?>
                <?php if ($s['store_id'] == $cur_store || $s['store_id'] == 0 ): ?>
                <li>
                <a href="<?php echo $path.'themeheros/banner7'.$imag;?>" title=""><img src="<?php echo $path.'themeheros/banner7'.$thumb_imag;?>" alt="" width= "50px"height= "50px"/></a>
                <?php if ($this->getConfig('description')){ ?>
                	<div class="captn-data">
                	<h2><?php echo $s['title'] ?></h2>
                	<?php echo $s['description'] ?>
                    </div>
                <?php } ?>
                </li>
                <?php $i++; endif; ?>
                <?php
                }//end if
                } // end foreach
                ?>
            
        </ul>
        <div id="controls"></div>
        <div class="clear"></div>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('card-sale')->toHtml(); ?>
    </div>
    
    <div class="clear"></div>
    <!--<div id="slideshow"></div>-->
</div>
<?php }?>