<?php if($this->canShow()): ?>
    <div class="under-breadcrumb">
        <?php foreach($this->getCollection() as $banner): ?>
            <div class="set">
                <a href="<?php echo $banner->getUrl() ?>" title="<?php echo $banner->getAltText() ?>" target="<?php echo $this->getTargetWindow() ?>">
                    <img src="<?php echo $banner->getImageUrl() ?>" width="1180" alt="<?php echo $banner->getAltText() ?>" />
                </a>
            </div>       
        <?php endforeach; ?>
    </div>  
<?php endif; ?>
