<div>	
	<h3><?php echo $this->__('Shipping Address')?></h3>
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
       <li class="wide">
           <label for="shipping-address-select" class="notice"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
           <div class="input-box">
               <?php echo $this->getAddressesHtmlSelect('shipping') ?>
           </div>
       </li>
    <?php endif ?>
        <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
            <fieldset>
                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                <input type="hidden" name="shipping[telephone]" value="<?php echo $this->escapeHtml(Mage::helper('web4pro_checkout')->getUserTelephone($this->getAddress())) ?>"  id="shipping:telephone"/>
                <ul>
                    <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->toHtml() ?></li>
                    <li class="fields">
                        <div class="fields">
                            <label for="shipping:company" class="required"><?php echo $this->__('Company') ?><em>*</em> :</label>
                            <div class="input-box">
                                <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('company') ?>"/>
                            </div>
                        </div>
                    </li>
            <?php $_streetValidationClass = $this->helper('opc')->getAttributeValidationClass('street'); ?>
                    <li class="wide checkout-block-type2">
                        <label for="shipping:street1" class="required"><?php echo $this->__('Address') ?><em>*</em> :</label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <li class="wide">
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
            <?php endfor; ?>
                    <?php if ($this->helper('opc')->isVatAttributeVisible()) : ?>
                    <li class="wide">
                        <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                        <div class="input-box">
                            <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('vat_id') ?>" />
                        </div>
                    </li>
                    <?php endif; ?>
                    <li class="fields checkout-block-type1">
                        <div class="field">
                            <label for="shipping:city" class="required"><?php echo $this->__('City') ?><em>*</em> :</label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('city') ?>" id="shipping:city" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:region" class="required"><?php echo $this->__('State/Province') ?><em>*</em> :</label>
                            <div class="input-box">
                                <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('region') ?>" style="display:none;" />
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:postcode" class="required"><?php echo $this->__('Zip/Postal Code') ?><em>*</em> :</label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('opc')->getAttributeValidationClass('postcode') ?>"  />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:country_id" class="required"><?php echo $this->__('Country') ?><em>*</em> :</label>
                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect('shipping') ?>
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <!--<div class="field">
                            <label for="shipping:fax"><?php /*echo $this->__('Fax') */?></label>
                            <div class="input-box">
                                <input type="text" name="shipping[fax]" value="<?php /*echo $this->escapeHtml($this->getAddress()->getFax()) */?>" title="<?php /*echo $this->__('Fax') */?>" class="input-text <?php /*echo $this->helper('opc')->getAttributeValidationClass('fax') */?>" id="shipping:fax"  />
                            </div>
                        </div>-->
                    </li>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <li class="control">
                        <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" <?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                <?php endif;?>
                </ul>
            </fieldset>
        </li>
        <li class="control">
            <input type="checkbox" name="billing[same_as_shipping]" onclick="billing.setSameAsShipping(this.checked);" id="billing:same_as_shipping" value="1" title="<?php echo $this->__('Use for Billing Address') ?>" class="checkbox" /><label for="billing:same_as_shipping"><?php echo $this->__('Use for Billing Address') ?></label>
        </li>
    </ul>

<script type="text/javascript">
    IWD.OPC.Checkout.clearOnChange = function(){};
    /** PULL PAYMENTS METHOD AFTER LOAD PAGE **/
    IWD.OPC.Checkout.pullPayments = function(){
        IWD.OPC.Checkout.lockPlaceOrder();
        IWD.OPC.Checkout.xhr = $j_opc.post(IWD.OPC.Checkout.config.baseUrl + 'onepage/json/payments',function(response){
            IWD.OPC.Checkout.xhr = null;

            if (typeof(response.error)!="undefined"){
                $j_opc('.opc-message-container').html(response.error);
                $j_opc('.opc-message-wrapper').show();
                IWD.OPC.saveOrderStatus = false;
                IWD.OPC.Checkout.hideLoader();
                IWD.OPC.Checkout.unlockPlaceOrder();
                return;
            }

            if (typeof(response.payments)!="undefined"){
                $j_opc('#checkout-payment-method-load').html(response.payments);
                jcf.replaceAll();
                payment.initWhatIsCvvListeners();
                IWD.OPC.bindChangePaymentFields();
                IWD.OPC.Decorator.setCurrentPaymentActive();
            };

            IWD.OPC.Checkout.pullReview();

        },'json');
    };
//<![CDATA[
    Billing.prototype.setSameAsShipping = function(flag){
        $('billing:same_as_shipping').checked = flag;
// #5599. Also it hangs up, if the flag is not false
//        $('billing:use_for_shipping_yes').checked = flag;
        if (flag) {
            this.syncWithShipping();
        }
    };
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');

    Billing.prototype.syncWithShipping = function () {
        $('shipping-address-select') && this.newAddress(!$('shipping-address-select').value);
       // $('shipping:same_as_billing').checked = true;
        if (!$('shipping-address-select') || !$('shipping-address-select').value) {
            arrElements = Form.getElements(this.form);
            for (var elemIndex in arrElements) {
                if (arrElements[elemIndex].id) {
                    var sourceField = $(arrElements[elemIndex].id.replace(/^billing:/, 'shipping:'));
                    if (sourceField) {
                        arrElements[elemIndex].value = sourceField.value;
                    }
                }
            }
            var valueCountry = $j_opc('#shipping-new-address-form select[name="shipping[country_id]"]').val();
            $j_opc('#opc-address-form-billing select[name="billing[country_id]"] [value="' + valueCountry + '"]').prop("selected", true);
            $j_opc('#opc-address-form-billing select[name="billing[region_id]"]').change();
            billingRegionUpdater.update();
            var valueRegionId = $j_opc('#shipping-new-address-form select[name="shipping[region_id]"]').val();
            $j_opc('#opc-address-form-billing select[name="billing[region_id]"] [value="' + valueRegionId + '"]').prop("selected", true);
            $j_opc('#opc-address-form-billing select[name="billing[country_id]"]').change();
        } else {
            $('billing-address-select').value = $('shipping-address-select').value;
        }
    };
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
//]]>

</script>
</div>