<?php 
	$params  = $this->getRequest()->getParams();
	$id = $params['id'];
	
	if(array_key_exists('productIds', $params)){
		$product_ids = $params['productIds'];
		
		if($product_ids){
			$product_ids = explode('|', $product_ids);
		}
	}else{
		$product_ids = array();
	}

	$is_last_level = $this->getData('is_last_level');
	
	if(!$is_last_level){
		$is_last_level = false;
	}
	
	$configurable_list = Mage::helper('template')->getAllConfigurableProducts();	
?>

<script type="text/javascript" src="/js/all/common/product.js"></script>
<?php $is_scp_enabled = Mage::getStoreConfig('dol/catalog_setting/scp_enabled');
if($is_scp_enabled){?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/scp_product_extension.js') ?>"></script>
<?php }?>
<script type="text/javascript">
//<![CDATA[
           
var optionsPrice;

jQuery.cachedScript = function(url, options) {
	// allow user to set any option except for dataType, cache, and url
	options = $j.extend(options || {}, {
	dataType: "script",
	cache: true,
	url: url
	});
	// Use $.ajax() since it is more flexible than $.getScript
	// Return the jqXHR object so we can chain callbacks
	return jQuery.ajax(options);
};
	
function getProductPricing(product_id){
	if(product_id!=undefined){
		url = '/catalog/product/ajaxsingle';
		document.getElementById('pricing').innerHTML = '<div align="center"><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"/><br /><br /></div>';

		$j.ajax({
			url: url,
			data: {'id':product_id},
			dataType: 'text',
			success: function(data) {	
				$j.cachedScript("/catalog/product/js/id/"+product_id)
					.done(function(script, textStatus) {
						productAddToCartForm = new VarienForm('product_addtocart_form');
						productAddToCartForm.submit = function(button, url) {
				            if (this.validator.validate()) {
				                var form = this.form;
				                var oldUrl = form.action;

				                document.getElementById('price_box_data').value = $$('div.price-box')[0].innerHTML;
				                
				                if (url) {
				                   form.action = url;
				                }
				                var e = null;
				                try {
				                    this.form.submit();
				                } catch (e) {
				                }
				                this.form.action = oldUrl;
				                if (e) {
				                    throw e;
				                }

				                if (button && button != 'undefined') {
				                    button.disabled = true;
				                }
				            }
				        }.bind(productAddToCartForm);

				        <?php $is_scp_enabled = Mage::getStoreConfig('dol/catalog_setting/scp_enabled');
						if($is_scp_enabled){?>
						$('product_addtocart_form').getElements().each(function(el) {
					        if(el.type == 'select-one') {
					            if(el.options && (el.options.length > 1)) {
					                el.options[0].selected = true;
					                spConfig.reloadOptionLabels(el);
					            }
					        }
					    });
					    <?php }?>

					    if(spConfig.settings[0]!=undefined && spConfig.settings[0].length>1){
							for(var i=0; i<10; i++){
								if(spConfig.settings[i]!=undefined){
									if(spConfig.settings[i].length>1){
										spConfig.settings[i].selectedIndex = 1;
										spConfig.configureElement(spConfig.settings[i]);
									}else{
										break;
									}
								}else{
									break;
								}
							}
					    }
				})
				data = data.replace(/[*]/g,"");
				data = data.replace("Required Fields","");
				data = data.replace("Availability: In stock.","");
				data = data.replace("availability","availability hide");
				data = data.replace("product-options","product-options no-margin-top");
				data = data.replace("class=\"label\" id=\"configurable-price-from", "class=\"label hide\" id=\"configurable-price-from");
				data = data.replace(/(\r\n|\n|\r)/gm,"");
				data = data.replace("p>            <div class=\"price-box\">","p> <div class=\"price-box hide\">");
				data = data.replace("regular-price","regular-price hide");
				data = data.replace("</div>        <label id=\"ajax_qty\"","<label id=\"ajax_qty\"");
				data = data.replace("</div>                <label id=\"ajax_qty\"","<label id=\"ajax_qty\"");
				data = data.replace("</div>                <label style=\"margin-left:50px;\" for=\"qty\" id=\"ajax_qty\"","<label style=\"margin-left:50px;\" for=\"qty\" id=\"ajax_qty\"");
				data = data.replace("</div>                <label for=\"qty\" style=\"margin-left:50px;\" id=\"ajax_qty\"","<label for=\"qty\" style=\"margin-left:50px;\" id=\"ajax_qty\"");
				
				data = data.replace("<div class=\"add-to-cart\">","</div><div class=\"add-to-cart\">");
				
				document.getElementById('pricing').innerHTML = data;
				decorateGeneric($$('#product-options-wrapper dl'), ['last']);
				
		
				jQuery("#cart_add").click(function(){
					cart_qty=parseInt(jQuery("#qty").val());
					jQuery("#qty").val(cart_qty+1);
					return false;
				});
					jQuery("#cart_remove").click(function(){
						cart_qty=parseInt(jQuery("#qty").val());
						if (cart_qty>0)
						jQuery("#qty").val(cart_qty-1);
						return false;
				});
				
				
			}
		});
	}
}

function removeRequiredClass(ab){
	$j("#plain_product").val(0);
	$j("input[type='file'].product-custom-option").removeClass('required-entry');
	$j("#advice-required-entry-options_1_file").addClass('validation-advice hide');
	
	productAddToCartForm.submit(ab);
}
function addRequiredClass(){
	$j("#plain_product").val(1);
	$j("#advice-required-entry-options_1_file").removeClass('validation-advice hide');
	$j("#advice-required-entry-options_1_file").addClass('validation-advice');
	$j("input[type='file'].product-custom-option").addClass('required-entry');
}
//]]>
</script>

	<div>
		<select id="configurable_product_id" name="configurable_product_id" onchange="getProductPricing(this.value);" class="sidebar-inner-select" style="display:none;">
			<?php
			  foreach($configurable_list as $product){
			  	
			  	if(!$is_last_level || !$product_ids || ($is_last_level && in_array($product->getId(), $product_ids))){
			 ?>
			<option value="<?php echo $product->getId()?>" ><?php echo Mage::helper('catalog')->__($product->getName());?></option>
			<?php
			  	}
			  } ?>
		</select>
		<div id="pricing"></div>
	</div>

<script type="text/javascript">
<!--
	getProductPricing($j("#configurable_product_id").first().val());
//-->
</script>
<script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    document.getElementById('price_box_data').value = $$('div.price-box')[0].innerHTML;
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
</script>

	
