<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.8
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */

?>
<section class="postlisting-blog bord-light">
<?php $post = $this->getPost(); ?>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<section class="postlisting-post">
    <div class="post-hedding">
        <h2 class="standart-title"><?php echo $post->getTitle(); ?></h2>
        <div class="tense"><span><?php echo $this->formatDate($post->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?>
        </span></div>
    </div>

    <div class="postContent std"><?php echo $post->getPostContent(); ?></div>
    <?php echo $this->getBookmarkHtml($post) ?>
     <div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
    <div class="postDetails">
        <?php $postCats = $post->getCats(); ?>
        <?php if (!empty($postCats)): ?>
            <?php echo Mage::helper('blog')->__('Posted in'); ?>
            <?php foreach ($postCats as $title => $url): ?>
                <a href="<?php echo $url; ?>"><?php echo $title; ?></a>
            <?php endforeach; ?>
        <?php else: ?>
            <?php echo Mage::helper('blog')->__('Posted'); ?>
        <?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?>
    </div>
</section>

<!-- Comment Section -->

<?php if ($this->getCommentsEnabled()): ?>
    <?php $comments = $this->getComment(); ?>

    <div class="postTitle standart-title">
        <h4><?php echo $this->__('Post Comments') ?><span class="quantity-comments"><?php echo "(".count($this->getComment()).")"; ?></span></h4>
    </div>
    <div class="comment-inform-outer">
<?php foreach ($comments as $comment) : ?>
            <div class="commentWrapper comment-inform">
                <div class="comment-inform-inner">
                     <div class="commentDetails"><span class="username"><?php echo $comment->getUser(); ?></span> <span class="tense"> <?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></span></div>
                <div class="commentContent"><?php echo nl2br($comment->getComment()); ?></div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>



    <?php if ($post->getComments()): ?>
        <div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
    <?php else: ?>
        <?php if ($this->getLoginRequired()): ?>
            <?php if ($this->helper('customer')->isLoggedIn()): ?>
                <form action="" id="postComment" method="post" class="post-form">
                    <fieldset class="group-select">
                        <div class="postTitle standart-title ">
                            <h4 class="legend"><?php echo Mage::helper('blog')->__('Submit Comment') ?></h4>
                        </div>
                        <ul class="form-list">
                            <li>

                                <div class="input-box aw-blog-comment-area">
                                    <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em><span class="colon">:</span></label><br />
                                    <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" ><?php echo $this->getCommentText(); ?></textarea>
                                </div>
                            </li>
                        </ul>
                    </fieldset>
                    <div class="button-set">
                        <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                        <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
                        <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
                        <span class="required"><?php echo $this->__('* Required Fields') ?></span>
                        <button class="form-button button btn" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                    </div>
                </form>

                <script type="text/javascript">
                    var contactForm = new VarienForm('postComment', false);
                </script>

            <?php else: ?>
                <p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
                <p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
            <?php endif ?>

        <?php else: ?>

            <form action="" id="postComment" method="post" class="post-form">
                <fieldset class="group-select">
                    <div class="postTitle standart-title">
                        <h4 class="legend"><?php echo Mage::helper('blog')->__('Submit Comment') ?></h4>
                    </div>
                    <ul class="form-list">
                        <li>

                            <div class="inputs">
                                <div class="input-box">
                                    <label for="name" class="required"><?php echo Mage::helper('blog')->__('Name') ?><em>*</em><span class="colon">:</span></label><br />
                                    <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" />
                                </div>

                                <div class="input-box">
                                    <label for="email" class="required"><?php echo Mage::helper('blog')->__('Email') ?><em>*</em><span class="colon">:</span></label><br />
                                    <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text" />
                                </div>

                            </div>

                            <div class="input-box aw-blog-comment-area">

                                <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em><span class="colon">:</span></label><br />
                                <textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" ><?php echo $this->getCommentText(); ?></textarea>

                            </div>
                        </li>

                        <?php
                        if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) {
                            ?><li><?php
                require_once 'recaptcha/recaptchalib-aw.php';

                // Get a key from http://recaptcha.net/api/getkey
                $publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
                $privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
                $error = null;

                echo recaptcha_get_html($publickey, $error, Mage::app()->getStore()->isCurrentlySecure());
                            ?></li><?php
            }
                        ?>
                    </ul>
                </fieldset>
                <div class="button-set">
                    <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                    <span class="required"><?php echo $this->__('* Required Fields') ?></span>
                    <button class="btn button form-button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                </div>
            </form>

            <script type="text/javascript">
                var contactForm = new VarienForm('postComment', false);
            </script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
</section>
