<div class="wrapper">
    <div class="page">
        <div class="main-container col3-layout">
            <div class="main">
                <div class="col-wrapper">
                    <div class="col-main">
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                    <div class="col-left sidebar"><?php echo $this->getChildHtml('left') ?></div>
                </div>
                <div class="col-right sidebar"><?php echo $this->getChildHtml('right') ?></div>
            </div>
        </div>
     </div>
</div>